export const FETCH_PLANETS = "FETCH_PLANETS";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_ERROR = "FETCH_PLANETS_ERROR";

export const FETCH_PLANET_DETAILS = "FETCH_PLANET_DETAILS";
export const FETCH_PLANET_DETAILS_SUCCESS = "FETCH_PLANET_DETAILS_SUCCESS";
export const FETCH_PLANET_DETAILS_ERROR = "FETCH_PLANET_DETAILS_ERROR";

export const FETCH_PLANET_ADDITIONS = "FETCH_PLANET_ADDITIONS";
export const FETCH_PLANET_ADDITIONS_SUCCESS = "FETCH_PLANET_ADDITIONS_SUCCESS";
export const FETCH_PLANET_ADDITIONS_ERROR = "FETCH_PLANET_ADDITIONS_ERROR";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const SHOW_TOAST = "SHOW_TOAST";
export const CLOSE_TOAST = "CLOSE_TOAST";
